CREATE TABLE `ansel-tracker_transaction_download_log` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text NOT NULL,
	`start_date` integer NOT NULL,
	`end_date` integer NOT NULL,
	`num_transactions` integer NOT NULL,
	`status` text NOT NULL,
	`error_message` text,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `ansel-tracker_plaid_account`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `ansel-tracker_transaction` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text NOT NULL,
	`plaid_transaction_id` text NOT NULL,
	`amount` real NOT NULL,
	`category` text,
	`merchant_name` text,
	`pending` integer DEFAULT false NOT NULL,
	`security_id` text,
	`ticker_symbol` text,
	`isin` text,
	`cusip` text,
	`sedol` text,
	`institution_security_id` text,
	`security_name` text,
	`security_type` text,
	`close_price` real,
	`close_price_as_of` integer,
	`is_cash_equivalent` integer,
	`type` text,
	`subtype` text,
	`iso_currency_code` text,
	`unofficial_currency_code` text,
	`market_identifier_code` text,
	`sector` text,
	`industry` text,
	`authorized_date` integer,
	`authorized_datetime` integer,
	`datetime` integer,
	`payment_channel` text,
	`transaction_code` text,
	`personal_finance_category` text,
	`merchant_entity_id` text,
	`location_address` text,
	`location_city` text,
	`location_region` text,
	`location_postal_code` text,
	`location_latitude` real,
	`location_longitude` real,
	`by_order_of` text,
	`payee` text,
	`payer` text,
	`payment_method` text,
	`payment_processor` text,
	`ppd_id` text,
	`reason` text,
	`reference_number` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `ansel-tracker_plaid_account`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `ansel-tracker_transaction_plaid_transaction_id_unique` ON `ansel-tracker_transaction` (`plaid_transaction_id`);